### ISSUE TITLE
Accueil - apparition au survol d'applats de couleurs

### ISSUE THREAD

**Issue by claireb** [m2dimi/marvel-colors#10]
Créer le code javascript pour la page d'accueil. Lorsque l'on survol avec la souris, une des flèches situées aux 4 coins de l'écran, un applat de couleur apparait.

![marvel colors - theme 1 - 0](https://cloud.githubusercontent.com/assets/5765213/5921418/1edd6f64-a644-11e4-8314-a914aced1a7f.png)
![marvel colors - theme 2 - 0](https://cloud.githubusercontent.com/assets/5765213/5921419/1edd9c8c-a644-11e4-9711-ba55ab42cc87.png)

**Comment by claire-mcn** [comment]
Fait !
