### ISSUE TITLE
Partie Series : accordeon

### ISSUE THREAD

**Issue by claireb** [m2dimi/marvel-colors#11]
Dans la partie "Series", coder l'accordeon qui se déploit au survol.

![marvel colors - theme 1 - detail - 2](https://cloud.githubusercontent.com/assets/5765213/5921450/50cc9d24-a644-11e4-81c2-ae9a0bfa444e.png)

**Comment by claire-mcn** [comment]
Finalement remplacé par des "cartes", qui se retournent au survol, comme ici : http://jsfiddle.net/videma/hgbmC/, depuis le revamp de la maquette "couleurs par série"

**Comment by claire-mcn** [comment]
Version "revamp" faite
